# Tarea 2. Práctica
## Realizado por: ROM

## 1. Métodos para resolver ecuaciones no lineales

Seleciona dos métodos de la siguiente lista y realiza el código correspondiente.
Cada código debe de mostrar las tablas de errores, 50 iteraciones y la tolerancia es de 4 decimales. La función a resolver es: "x^3 + 4*(x^2) - 10" en el intervalo [0, 1]

(a) Método de la Falsa Posición.

(b) Método de Newton Modificado.

(c) Método de Punto Fijo.

(d) Método de la Secante.

### Librerías a utilizar

In [1]:
# Nos ayuda a hacer matemáticas simbólicas
# Por ejemplo, para sacar derivadas o sustituir valores en una función previamente definida
import sympy as sp

# Nos ayuda a utilizar matrices y varias de sus operaciones
import numpy as np

# Nos ayuda a imprimir tablas ordenadas
import tabulate as tb

from logging import log
from math import exp

### (a) Método de la Falsa Posición.

In [2]:
def metodo_falsa_posicion(f, a, b, tol):
  # f: Función a resolver
  # a: Límite inferior del intervalo [a, b]
  # b: Límite superior del intervalo [a, b]
  # tol: Tolerancia

  # Tabla (matriz) con las 50 iteraciones o menos, y los errores entre cada iteración
  tabla_iteraciones = np.array(["Iteración", "a", "f(a)", "b", "f(b)","x_i", "f(x_i)", "Error Absoluto", "Error Relativo"])
  iteracion = []

  # Número iteración
  i = 1

  # Para ver si nos salimos del bucle antes de las 50 iteraciones
  continuar = True

  # Mientras el número de iteraciones sea menor o igual a 50
  # y mientras el error sea mayor a la tolerancia
  while (i<=50 and continuar):
    # Evaluamos la función f en a y b
    fa = f(a)
    #print("f(a): ", fa)

    fb = f(b)
    #print("f(b): ", fb)

    #### CRITERIO DE CAMBIO DE SIGNO ####
    if(fa * fb < 0):
      # Si existe un cambio de signo entre f(a) y f(b) realizamos el método

      # Calculamos el valor de c_i
      c_i = a - fa * ((b - a) / (fb - fa))
      c_i = float(c_i)
      #print("c_i: ", c_i)

      # Evaluamos la función en c_i
      fc = f(c_i) # f(c_i)
      #print("f(c): ", fc)

      error_absoluto = 1
      error_relativo = 1

      # Calculamos el error absoluto y el relativo
      if(i == 1):
        iteracion = [i, a, fa, b, fb, c_i, fc, None, None]
      else:
        c_i_ant = tabla_iteraciones[i-1][5]
        #print("c_i_ant: ", c_i_ant)

        error_absoluto = abs(c_i - c_i_ant)
        #print("Error Absoluto: ", error_absoluto)
        error_relativo = (c_i - c_i_ant) / c_i

        iteracion = [i, a, fa, b, fb, c_i, fc, error_absoluto, error_relativo]

      # Si el error absoluto es menor o igual a la tolerancia, nos detenemos
      if(error_absoluto <= tol):
        print("\nRaíz encontrada con la tolerancia deseada.")
        continuar = False

      # Agregamos la nueva iteración a una nueva fila en la tabla de errores
      tabla_iteraciones = np.vstack((tabla_iteraciones, iteracion))

      #### CRITERIO PARA CONTINUAR ITERACIONES ####
      if(fc == 0):
        # Si f(c) es igual a cero, nos detenemos
        print("\nRaíz encontrada.")
        continuar = False
      elif(fa * fc < 0):
        # Si f(a) * f(c) es menor a cero, existe cambio de signo entre ellos
        b = c_i
      elif(fb * fc < 0):
        # Si f(b) * f(c) es menor a cero, existe cambio de signo entre ellos
        a = c_i

    else:
      # Si no existe un cambio de signo entre f(a) y f(b) nos detenemos
      continuar = False
      print("\nNo existe un cambio de signo entre f(a) y f(b).")
      iteracion = [i, a, fa, b, fb, None, None, None, None]

    # Agregamos la nueva iteración a una nueva fila en la tabla de errores
      tabla_iteraciones = np.vstack((tabla_iteraciones, iteracion))

    # Aumentamos en 1 el número de la iteración
    i +=1

  # Una vez salimos del while, regresamos la tabla de errores
  return tabla_iteraciones


### (d) Método de la Secante

In [3]:
def metodo_secante(f, a, b, tol):
  # f: Función a resolver
  # a: Límite inferior del intervalo [a, b]
  # b: Límite superior del intervalo [a, b]
  # tol: Tolerancia

  # Tabla (matriz) con las 50 iteraciones o menos, y los errores entre cada iteración
  tabla_iteraciones = np.array(["Iteración", "x_i", "f(x_i)", "Error Absoluto", "Error Relativo"])
  iteracion = []

  # x_0
  iteracion = [0, a, f(a), None, None]
  tabla_iteraciones = np.vstack((tabla_iteraciones, iteracion))

  # x_1
  error_absoluto = abs(b - a)
  error_relativo = (b - a) / b
  iteracion = [1, b, f(b), error_absoluto, error_relativo]
  tabla_iteraciones = np.vstack((tabla_iteraciones, iteracion))

  # Número iteración
  i = 2

  # Para ver si nos salimos del bucle antes de las 50 iteraciones
  continuar = True

  # Mientras el número de iteraciones sea menor o igual a 50
  # y mientras el error sea mayor a la tolerancia
  while (i<=50 and continuar):
    # Evaluamos la función f en a y b
    fa = f(a)
    #print("f(a): ", fa)

    fb = f(b)
    #print("f(b): ", fb)

    # Calculamos el valor de c_i
    c_i = a - fa * ((b - a) / (fb - fa))
    c_i = float(c_i)
    #print("c_i: ", c_i)

    # Evaluamos la función en c_i
    fc = f(c_i) # f(c_i)
    #print("f(c): ", fc)

    # Error Absoluto
    error_absoluto = abs(c_i - b)
    #print("Error Absoluto: ", error_absoluto)

    # Error Relativo
    error_relativo = (c_i - b) / c_i

    iteracion = [i, c_i, fc, error_absoluto, error_relativo]

    # Si el error absoluto es menor o igual a la tolerancia, nos detenemos
    if(error_absoluto <= tol):
      print("\nRaíz encontrada con la tolerancia deseada.")
      continuar = False

    # Agregamos la nueva iteración a una nueva fila en la tabla de errores
    tabla_iteraciones = np.vstack((tabla_iteraciones, iteracion))

    #### CRITERIO PARA CONTINUAR ITERACIONES ####
    if(fc == 0):
      # Si f(c) es igual a cero, nos detenemos
      print("\nRaíz encontrada.")
      continuar = False
    else:
      a = b
      b = c_i

    # Aumentamos en 1 el número de la iteración
    i +=1

  # Una vez salimos del while, regresamos la tabla de errores
  return tabla_iteraciones

### Ejemplo

#### Definimos las ecuaciones no lineales como funciones

In [4]:
def funcion(x):
  f_x = x**3 + 4*(x**2) - 10
  f_x = float(f_x)
  return f_x

#### Resolvemos las ecauciones no lineales por ambos métodos, mostrando la tabla de errores

In [5]:
# Ejemplo
print("\t #### EJEMPLO DE LA TAREA ####\n")

# Definimos la función
f = "x**3 + 4*(x**2) - 10"
print("Función: ", f)

# Decimos de cuanto es la tolerancia
tolerancia = 1*(10**(-4))
print("Tolerancia: ", tolerancia)

# Intervalo
a = 0
b = 2
print("Intervalo: [", a, ", ", b, "]")

# ------------------------------------------------------------------------------
#### Método Falsa Posición ####
print()
print("\tMétodo Falsa Posición:")

# Llamamos al método de la falsa posición
metodo1 = metodo_falsa_posicion(funcion, a, b, tolerancia)

# Imprime como tabla la información
print(tb.tabulate(metodo1, tablefmt="fancy_grid"))

# ------------------------------------------------------------------------------
#### Método de la Secante ####
print()
print("\tMétodo de la Secante:")

# Llamamos al método de la falsa posición
metodo2 = metodo_secante(funcion, a, b, tolerancia)

# Imprime como tabla la información
print(tb.tabulate(metodo2, tablefmt="fancy_grid"))

	 #### EJEMPLO DE LA TAREA ####

Función:  x**3 + 4*(x**2) - 10
Tolerancia:  0.0001
Intervalo: [ 0 ,  2 ]

	Método Falsa Posición:

Raíz encontrada con la tolerancia deseada.
╒═══════════╤════════════════════╤════════════════════════╤═════╤══════╤════════════════════╤════════════════════════╤═══════════════════════╤════════════════════════╕
│ Iteración │ a                  │ f(a)                   │ b   │ f(b) │ x_i                │ f(x_i)                 │ Error Absoluto        │ Error Relativo         │
├───────────┼────────────────────┼────────────────────────┼─────┼──────┼────────────────────┼────────────────────────┼───────────────────────┼────────────────────────┤
│ 1         │ 0                  │ -10.0                  │ 2   │ 14.0 │ 0.8333333333333333 │ -6.643518518518519     │                       │                        │
├───────────┼────────────────────┼────────────────────────┼─────┼──────┼────────────────────┼────────────────────────┼───────────────────────┼───────────

## 2. Características de una Matriz

Cree un código para identificar cuando una matriz A es cuadrada, cuando es invertible, es decir, su determinante es diferente de cero, cuando es simétrica y definida positiva, es decir si todos sus eigenvalores de A son positivos.

### Librerías a utilizar

In [6]:
# Nos ayuda a utilizar matrices y varias de sus operaciones
import numpy as np

### Creamos una función que nos diga algunas características de la matriz

In [7]:
def carac_matriz(matriz):

  #### TAMAÑO MATRIZ ####
  # Te dice cuántas filas tiene la matriz
  numfilas = matriz.shape[0]

  # Te dice cuántas columnas tiene la matriz
  numcolumnas = matriz.shape[1]

  # print("Filas: ", numfilas)
  # print("Columnas: ", numcolumnas)

  #### ¿ES CUADRADA LA MATRIZ? ####
  # ¿El número de filas es igual al número de columnas?
  es_cuadrada = (numfilas == numcolumnas)

  if(es_cuadrada):
    # Si el número de filas es igual al número de columnas
    # La matriz si es cuadrada
    # print("Es Cuadrada: ", es_cuadrada)

    #### DETERMINANTE ####
    # Te dice el determinante de la matriz
    determinante = np.linalg.det(matriz)
    # print("Determinante: ", determinante)

    #### ¿ES INVERTIBLE LA MATRIZ? ####
    # ¿El determinante de la matriz es diferente de cero?
    es_invertible = (determinante != 0)
    # Si el determinante de la matriz es diferente de cero, entonces la matriz es invertible
    # Si el determinante de la matriz es igual a cero, entonces la matriz no es invertible
    # print("Es Invertible: ", es_invertible)

    #### ¿ES SIMÉTRICA  LA MATRIZ? ####
    # Obtenemos la matriz traspuesta
    matriz_traspuesta = matriz.T
    print("Matriz Transpuesta:\n", matriz_traspuesta)

    # ¿La matriz es simétrica?
    es_simetrica = np.array_equal(matriz, matriz_traspuesta)
    # Si la matriz es igual a su traspuesta, entonces la matriz es simétrica
    # Si la matriz es igual a su traspuesta, entonces la matriz no es simétrica
    # print("Es Simétrica: ", es_simetrica)

    #### ¿ES DEFINIDA POSITIVA LA MATRIZ? ####
    # Una matriz cuadrada A es definida positiva si cumple que:
    # 1. A es simétrica
    # 2. Si todos sus eigenvalores son positivos.
    es_definida_positiva = 0
    if(es_simetrica):
      # Si la matriz es simétrica, entonces obtenemos sus eigenvalores
      eigenvalores = np.linalg.eigvals(matriz)
      print("\nEigenvalores: ", eigenvalores)
      # ¿Todos los eigenvalores son positivos?
      es_definida_positiva = np.all(eigenvalores > 0)
      # print("Es definida positiva: ", es_definida_positiva)
    else:
      # Si la matriz no es simétrica, entonces no es definida positiva
      eigenvalores = False
      # print("Eigenvalores: ", eigenvalores)
      es_definida_positiva = False
      # print("Es Definida Positiva: ", es_definida_positiva)

    carac = np.array([["NúmeroFilas", "NúmeroColumnas", "EsCuadrada", "Determinante", "EsInvertible", "EsSimétrica", "EsDefinidaPositiva"],
                      [numfilas,           numcolumnas,  es_cuadrada,   determinante,  es_invertible,  es_simetrica, es_definida_positiva]])

  else:
    # Si el número de filas es diferente al número de columnas
    # La matriz no es cuadrada
    # print("Es Cuadrada: ", es_cuadrada)

    carac = np.array([["NúmeroFilas", "NúmeroColumnas", "EsCuadrada"],
                      [numfilas,           numcolumnas,  es_cuadrada]])


  return carac

### Ejemplos de uso


In [8]:
# Ejemplo
print("\t #### EJEMPLO DE LA TAREA ####")

matriz = np.array([ [2, 0, -1],
                    [0, 2, 1],
                    [-1, 1, 2] ])

print("\nMatriz:\n", matriz)

print()
carac = carac_matriz(matriz)

print()
print("Lo que obtenemos de la función:")
print(carac)

# Columnas en el array "carac"
col = carac.shape[1]

# Imprimimos las características de la matriz
print()
print("Características de la matriz:")
for i in range(col):
  print("+ ", carac[0, i], ": ", carac[1, i])
  # carac[0, i] <- Nombre de la característica
  # carac[1, i] <- Valor de la característica

print()
print("--------------------------------------------------------")

print("\t #### OTRO EJEMPLO, MATRIZ NO CUADRADA ####")
matriz1 = np.array([ [2, 0, -1],
                    [0, 2, 1] ])

print("\nMatriz:\n", matriz1)

print()
carac1 = carac_matriz(matriz1)

print()
print("Lo que obtenemos de la función:")
print(carac1)

# Columnas en el array "carac1"
col1 = carac1.shape[1]

# Imprimimos las características de la matriz
print()
print("Características de la matriz:")
for i in range(col1):
  print("+ ", carac1[0, i], ": ", carac1[1, i])
  # carac[0, i] <- Nombre de la característica
  # carac[1, i] <- Valor de la característica

	 #### EJEMPLO DE LA TAREA ####

Matriz:
 [[ 2  0 -1]
 [ 0  2  1]
 [-1  1  2]]

Matriz Transpuesta:
 [[ 2  0 -1]
 [ 0  2  1]
 [-1  1  2]]

Eigenvalores:  [3.41421356 2.         0.58578644]

Lo que obtenemos de la función:
[['NúmeroFilas' 'NúmeroColumnas' 'EsCuadrada' 'Determinante'
  'EsInvertible' 'EsSimétrica' 'EsDefinidaPositiva']
 ['3' '3' 'True' '4.0' 'True' 'True' 'True']]

Características de la matriz:
+  NúmeroFilas :  3
+  NúmeroColumnas :  3
+  EsCuadrada :  True
+  Determinante :  4.0
+  EsInvertible :  True
+  EsSimétrica :  True
+  EsDefinidaPositiva :  True

--------------------------------------------------------
	 #### OTRO EJEMPLO, MATRIZ NO CUADRADA ####

Matriz:
 [[ 2  0 -1]
 [ 0  2  1]]


Lo que obtenemos de la función:
[['NúmeroFilas' 'NúmeroColumnas' 'EsCuadrada']
 ['2' '3' 'False']]

Características de la matriz:
+  NúmeroFilas :  2
+  NúmeroColumnas :  3
+  EsCuadrada :  False
